#!/bin/sh
### BEGIN INIT INFO
# Provides:          Qubie
# Required-Start:    $all
# Required-Stop:     $local_fs $network $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Qubie at boot time
# Description:       Starts the Qubie monitoring service.
### END INIT INFO

# change this to your Qubie root directory
dir="/usr/local/qubie"

# change this to the WiFi interface you want Qubie to monitor
interface="wlan1"

# change this to include your desired command line options
options="-w whitelist-ouis -e -m 1 -s -B"

# you should not need to change anything below this line under normal usage scenarios

logsuffix=`date +"%Y%m%d_%H%M"`
monitorcmd="iwconfig $interface mode monitor"
hashes="" # -H $dir/data/hashes-$logsuffix.csv  if you want to log hashes
          # note that logging hashes eliminates privacy!
cmd="./qubie_wifi.py -i $interface -l $dir/log/qubie-$logsuffix.log -c $dir/data/num-$logsuffix.csv -r $dir/data/range-$logsuffix.csv -C $dir/data/contacts-$logsuffix.csv $options $hashes"
user=""

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

wait_for_bluetooth() {
    while [ ! "`ps -ef | grep bluetoothd | grep -v grep`" ]; do
      sleep 5
    done
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        sudo mkdir -p "$dir/log"
        sudo mkdir -p "$dir/data" 
        cd "$dir"    
        
        wait_for_bluetooth   
        sudo $monitorcmd >> "$stdout_log" 2>> "$stderr_log"
        
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        sudo echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in `seq 1 20`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
